AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  simple-api

  Sample SAM Template for simple-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
        HelloEcho:
          Type: Api
          Properties:
            Path: /hello
            Method: post
  storesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: stores.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        getStores:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /stores
            Method: get
        addStore:
          Type: Api
          Properties:
            Path: /stores
            Method: post
      Policies:
        - DynamoCrudPolicy:
          TableName: !Ref Stores
    Environment:
      TABLE_NAME: !Ref Stores

  # Stores Table
  StoresTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Stores
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: store_id
          AttributeType: S
      KeySchema:
        - AttributeName: store_id
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true

  # Items Table (Stores Inventory & Order Items)
  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Items
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: store_id
          AttributeType: S
        - AttributeName: item_id
          AttributeType: S
      KeySchema:
        - AttributeName: store_id
          KeyType: HASH
        - AttributeName: item_id
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
      GlobalSecondaryIndexes:
        - IndexName: ItemTypeIndex
          KeySchema:
            - AttributeName: item_type
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # Orders Table
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Orders
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: store_id
          AttributeType: S
        - AttributeName: order_id
          AttributeType: S
      KeySchema:
        - AttributeName: store_id
          KeyType: HASH
        - AttributeName: order_id
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  storesApi:
    Description: "API Gateway endpoint URL for Prod stage for stores function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/stores/"
  storesFunction:
    Description: "Stores Lambda Function ARN"
    Value: !GetAtt storesFunction.Arn
  storesIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt storesFunctionRole.Arn
