name: Deploy AWS Lambda

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        FUNCTIONS=("items" "orders" "stores")
        for FUNCTION in "${FUNCTIONS[@]}"; do
          pip install -r requirements.txt -t lambda/$FUNCTION
          zip -r "$FUNCTION.zip" "./lambda/$FUNCTION"
          aws lambda update-function-code \
            --function-name "$FUNCTION" \
            --zip-file fileb://$FUNCTION.zip \
            --region $AWS_REGION
          echo "✅ Updated $FUNCTION"
        done
